version: "2"

services:
  redis:
    image: redis:3.2
    ports:
      - "16379:6379"
    hostname: redis
  elasticsearch:
    image: elasticsearch:5.6.8
    ports:
      - "19200:9200"
    environment:
      - xpack.security.enabled=false
      - script.inline=true
      - ES_JAVA_OPTS=-Xms32M -Xmx128M
    hostname: es
