version: '3'

# Reference. https://docs.traefik.io/getting-started/quick-start/
# 1. launch the traefik reverse-proxy with 'docker-compose up -d traefik'
# 2. launch 2 instances of sirius-chat with 'docker-compose up -d scale sirius-chat-sample=2'

services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Add a configuration pretty much like the reverse-proxy from the reference

  # sirius-chat
  sirius-chat-sample:
    # The sirius-chat image built with the provided Dockerfile
    image: sirius-chat
    # Add a configuration for the sirius-chat image
    # Hint: traefik.http.routers.sirius-chat-sample.rule=PathPrefix(`/`)
